[[bindings]]
key = '1'
modifiers = ['command']
command = ['open', '-a', 'alacritty']

[[bindings]]
key = '2'
modifiers = ['command']
command = ['open', '-a', 'safari']


[[bindings]]
key = '3'
modifiers = ['command']
command = ['open', '-a', 'terminal']

[[bindings]]
key = 'Return'
modifiers = ['command']
command = ['open', '-na', 'terminal']

[[bindings]]
key = 'g'
modifiers = ['command']
command = ['open', 'http://google.com']

[[bindings]]
key = 'j'
modifiers = ['command']
command = ['open', 'http://google.com']




