[package]
name = "HKDM"
version = "0.1.0"
edition = "2024"

[dependencies]
getopts = "*"
libc = "*"
env_logger = "*"
log = "*"
rdev = "0.5"
serde = {version = "1.0.219", features = ["derive"] }
toml = "0.8.22"

